//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBRequests : DbContext
    {
        public DBRequests()
            : base("name=DBRequests")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ViewAllRequest> ViewAllRequest { get; set; }
        public virtual DbSet<ViewGroupProblem> ViewGroupProblem { get; set; }
    
        public virtual ObjectResult<RequestsOfMasterName_Result> RequestsOfMasterName(string master)
        {
            var masterParameter = master != null ?
                new ObjectParameter("Master", master) :
                new ObjectParameter("Master", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestsOfMasterName_Result>("RequestsOfMasterName", masterParameter);
        }
    
        public virtual ObjectResult<RequestsOfMasterNumber_Result> RequestsOfMasterNumber(Nullable<int> master)
        {
            var masterParameter = master.HasValue ?
                new ObjectParameter("Master", master) :
                new ObjectParameter("Master", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestsOfMasterNumber_Result>("RequestsOfMasterNumber", masterParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CountRequestsReady()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CountRequestsReady");
        }
    
        public virtual int AvgRequestsReady()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AvgRequestsReady");
        }
    }
}
